version: '2.1'
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1
    steps:
      - checkout
      - ruby/install-deps
  lint:
    docker:
      - image: cimg/ruby:3.0.1
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Linter
          command: bundle exec rake standard
  test:
    docker:
      - image: cimg/ruby:3.0.1
      - environment:
          POSTGRES_DB: pokemon_patterns_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: circleci-user
        image: cimg/postgres:15.2
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: circleci-user
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

workflows:
  build_and_test:
    jobs:
      - build
      - lint
      - test
